package com.example.util

import com.example.data.model.AppLanguage

object Localization {
    private val enStrings = mapOf(
        "app_title" to "Messenger",
        "chats" to "Chats",
        "calls" to "Calls",
        "stories" to "Stories",
        "people" to "People",
        "ai_assistant" to "AI Assistant",
        "settings" to "Settings",
        "search_hint" to "Search messages, people, groups...",
        "type_message" to "Type a message...",
        "online" to "Active now",
        "offline" to "Offline",
        "last_seen" to "Last seen",
        "typing" to "is typing...",
        "pinned_message" to "Pinned Message",
        "replying_to" to "Replying to",
        "send" to "Send",
        "cancel" to "Cancel",
        "save" to "Save",
        "delete" to "Delete",
        "delete_for_me" to "Delete for me",
        "delete_for_everyone" to "Delete for everyone",
        "edit_message" to "Edit message",
        "copy" to "Copy",
        "forward" to "Forward",
        "reply" to "Reply",
        "pin" to "Pin",
        "unpin" to "Unpin",
        "bookmark" to "Save message",
        "unbookmark" to "Unsave message",
        "mute" to "Mute notifications",
        "unmute" to "Unmute",
        "archive" to "Archive",
        "unarchive" to "Unarchive",
        "block" to "Block user",
        "unblock" to "Unblock",
        "report" to "Report",
        "clear_chat" to "Clear chat",
        "delete_chat" to "Delete conversation",
        "create_group" to "New Group",
        "group_name" to "Group name",
        "group_desc" to "Description",
        "add_members" to "Add members",
        "members" to "Members",
        "admin" to "Admin",
        "owner" to "Owner",
        "make_admin" to "Make Admin",
        "remove_admin" to "Dismiss as Admin",
        "remove_member" to "Remove from group",
        "leave_group" to "Leave group",
        "only_admins_message" to "Only admins can send messages",
        "voice_call" to "Voice Call",
        "video_call" to "Video Call",
        "calling" to "Calling...",
        "ringing" to "Ringing...",
        "call_ended" to "Call Ended",
        "incoming_call" to "Incoming Call",
        "accept" to "Accept",
        "decline" to "Decline",
        "my_story" to "Your Story",
        "add_story" to "Add to Story",
        "create_story" to "Create Story",
        "story_privacy" to "Story Privacy",
        "everyone" to "Everyone",
        "contacts_only" to "Contacts only",
        "only_me" to "Only me",
        "text_story" to "Text",
        "image_story" to "Media",
        "wallet" to "Messenger Pay",
        "send_money" to "Send Money",
        "request_money" to "Request",
        "amount" to "Amount",
        "note" to "What is this for?",
        "balance" to "Available Balance",
        "transactions" to "Transactions",
        "admin_panel" to "Admin Dashboard",
        "analytics" to "System Analytics",
        "total_users" to "Total Users",
        "active_users" to "Active Users",
        "total_messages" to "Total Messages",
        "storage_usage" to "Storage Usage",
        "reports_queue" to "Pending Reports",
        "ban_user" to "Ban User",
        "unban_user" to "Unban User",
        "e2ee_notice" to "Messages are end-to-end encrypted. No one outside of this chat can read them.",
        "verified_security_code" to "Verified Security Fingerprint",
        "login" to "Log In",
        "register" to "Create Account",
        "email" to "Email address",
        "password" to "Password",
        "name" to "Full Name",
        "username" to "Username",
        "phone" to "Phone number",
        "forgot_password" to "Forgot password?",
        "dont_have_account" to "Don't have an account? Sign Up",
        "already_have_account" to "Already have an account? Log In",
        "logout" to "Log Out",
        "profile" to "Profile",
        "edit_profile" to "Edit Profile",
        "bio" to "Bio",
        "active_status" to "Active Status",
        "show_active_status" to "Show when you're active",
        "language" to "Language",
        "theme" to "Appearance",
        "privacy_security" to "Privacy & Security",
        "notifications_sounds" to "Notifications & Sounds",
        "media_files" to "Shared Media & Files",
        "voice_recorded" to "Voice message",
        "recording_audio" to "Recording audio...",
        "hold_to_record" to "Tap or hold mic to record",
        "slide_to_cancel" to "Slide to cancel",
        "no_messages" to "No messages yet. Say hello! 👋",
        "no_chats" to "No conversations found",
        "no_calls" to "No recent calls",
        "no_stories" to "No recent stories from friends",
        "ai_help_prompt" to "Ask AI for quick replies, writing help, or translation"
    )

    private val bnStrings = mapOf(
        "app_title" to "মেসেঞ্জার",
        "chats" to "চ্যাট",
        "calls" to "কল",
        "stories" to "স্টোরি",
        "people" to "মানুষজন",
        "ai_assistant" to "এআই অ্যাসিস্ট্যান্ট",
        "settings" to "সেটিংস",
        "search_hint" to "মেসেজ, মানুষ বা গ্রুপ খুঁজুন...",
        "type_message" to "মেসেজ লিখুন...",
        "online" to "এখন সক্রিয়",
        "offline" to "অফলাইন",
        "last_seen" to "সর্বশেষ দেখা গেছে",
        "typing" to "টাইপ করছে...",
        "pinned_message" to "পিন করা বার্তা",
        "replying_to" to "উত্তর দিচ্ছেন",
        "send" to "পাঠান",
        "cancel" to "বাতিল",
        "save" to "সংরক্ষণ",
        "delete" to "মুছুন",
        "delete_for_me" to "আমার জন্য মুছুন",
        "delete_for_everyone" to "সবার জন্য মুছুন",
        "edit_message" to "মেসেজ এডিট করুন",
        "copy" to "কপি",
        "forward" to "ফরওয়ার্ড",
        "reply" to "রিপ্লাই",
        "pin" to "পিন করুন",
        "unpin" to "আনপিন করুন",
        "bookmark" to "মেসেজ সংরক্ষণ করুন",
        "unbookmark" to "সংরক্ষণ সরান",
        "mute" to "মিউট করুন",
        "unmute" to "আনমিউট করুন",
        "archive" to "আর্কাইভ",
        "unarchive" to "আনআর্কাইভ",
        "block" to "ব্লক করুন",
        "unblock" to "আনব্লক করুন",
        "report" to "রিপোর্ট করুন",
        "clear_chat" to "চ্যাট পরিষ্কার করুন",
        "delete_chat" to "চ্যাট ডিলিট করুন",
        "create_group" to "নতুন গ্রুপ",
        "group_name" to "গ্রুপের নাম",
        "group_desc" to "বিবরণ",
        "add_members" to "সদস্য যোগ করুন",
        "members" to "সদস্যবৃন্দ",
        "admin" to "অ্যাডমিন",
        "owner" to "মালিক",
        "make_admin" to "অ্যাডমিন বানান",
        "remove_admin" to "অ্যাডমিন সরান",
        "remove_member" to "গ্রুপ থেকে সরান",
        "leave_group" to "গ্রুপ ত্যাগ করুন",
        "only_admins_message" to "শুধু অ্যাডমিন মেসেজ পাঠাতে পারবে",
        "voice_call" to "ভয়েস কল",
        "video_call" to "ভিডিও কল",
        "calling" to "কল হচ্ছে...",
        "ringing" to "রিং হচ্ছে...",
        "call_ended" to "কল সমাপ্ত",
        "incoming_call" to "ইনকামিং কল",
        "accept" to "গ্রহণ করুন",
        "decline" to "প্রত্যাখ্যান",
        "my_story" to "আপনার স্টোরি",
        "add_story" to "স্টোরি যোগ করুন",
        "create_story" to "স্টোরি তৈরি করুন",
        "story_privacy" to "স্টোরি প্রাইভেসী",
        "everyone" to "সবাই",
        "contacts_only" to "শুধু পরিচিতরা",
        "only_me" to "শুধু আমি",
        "text_story" to "টেক্সট",
        "image_story" to "মিডিয়া",
        "wallet" to "মেসেঞ্জার পে",
        "send_money" to "টাকা পাঠান",
        "request_money" to "অনুরোধ করুন",
        "amount" to "পরিমাণ",
        "note" to "কীসের জন্য?",
        "balance" to "বর্তমান ব্যালেন্স",
        "transactions" to "লেনদেন ইতিহাস",
        "admin_panel" to "অ্যাডমিন ড্যাশবোর্ড",
        "analytics" to "সিস্টেম বিশ্লেষণ",
        "total_users" to "মোট ব্যবহারকারী",
        "active_users" to "সক্রিয় ব্যবহারকারী",
        "total_messages" to "মোট মেসেজ",
        "storage_usage" to "স্টোরেজ ব্যবহার",
        "reports_queue" to "পেন্ডিং রিপোর্ট",
        "ban_user" to "ব্যবহারকারী ব্যান করুন",
        "unban_user" to "আনব্যান করুন",
        "e2ee_notice" to "মেসেজগুলো অ্যান্ড-টু-অ্যান্ড এনক্রিপ্ট করা। চ্যাটের বাইরে কেউ এগুলো পড়তে পারবে না।",
        "verified_security_code" to "ভেরিফাইড সিকিউরিটি কোড",
        "login" to "লগ ইন",
        "register" to "নতুন অ্যাকাউন্ট খুলুন",
        "email" to "ইমেইল এড্রেস",
        "password" to "পাসওয়ার্ড",
        "name" to "সম্পূর্ণ নাম",
        "username" to "ইউজারনেম",
        "phone" to "ফোন নম্বর",
        "forgot_password" to "পাসওয়ার্ড ভুলে গেছেন?",
        "dont_have_account" to "অ্যাকাউন্ট নেই? সাইন আপ করুন",
        "already_have_account" to "অ্যাকাউন্ট আছে? লগ ইন করুন",
        "logout" to "লগ আউট",
        "profile" to "প্রোফাইল",
        "edit_profile" to "প্রোফাইল এডিট করুন",
        "bio" to "বায়ো",
        "active_status" to "অ্যাক্টিভ স্ট্যাটাস",
        "show_active_status" to "সক্রিয় থাকলে প্রদর্শন করুন",
        "language" to "ভাষা (Language)",
        "theme" to "থিম ও ডিসপ্লে",
        "privacy_security" to "প্রাইভেসি ও নিরাপত্তা",
        "notifications_sounds" to "নোটিফিকেশন ও সাউন্ড",
        "media_files" to "শেয়ার করা মিডিয়া ও ফাইল",
        "voice_recorded" to "ভয়েস বার্তা",
        "recording_audio" to "অডিও রেকর্ড হচ্ছে...",
        "hold_to_record" to "ভয়েস রেকর্ডের জন্য চাপুন",
        "slide_to_cancel" to "বাতিল করতে স্লাইড করুন",
        "no_messages" to "কোনো মেসেজ নেই। হাই বলুন! 👋",
        "no_chats" to "কোনো চ্যাট পাওয়া যায়নি",
        "no_calls" to "কোনো সাম্প্রতিক কল নেই",
        "no_stories" to "বন্ধুদের কোনো নতুন স্টোরি নেই",
        "ai_help_prompt" to "দ্রুত রিপ্লাই, অনুবাদ বা লেখার সাহায্যের জন্য এআইকে বলুন"
    )

    fun getString(key: String, lang: AppLanguage = AppLanguage.ENGLISH): String {
        return when (lang) {
            AppLanguage.BENGALI -> bnStrings[key] ?: enStrings[key] ?: key
            AppLanguage.ENGLISH -> enStrings[key] ?: key
        }
    }
}
